name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Corepack
        run: npm i -g corepack@latest && corepack enable
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm i --frozen-lockfile
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}